version: "3.9"

services:
    web_api:
        image: web_api
        container_name: web_api_application
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        volumes:
              - $APPDATA/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
        ports:
            - "5000:80"